---
driver:
    name: docker
    use_sudo: false
    privileged: true

provisioner:
    name: salt_solo
    formula: beats
    salt_install: bootstrap
    salt_bootstrap_options: -X stable
    salt_bootstrap_url: https://raw.githubusercontent.com/saltstack/salt-bootstrap/stable/bootstrap-salt.sh
    require_chef: false
    state_top:
        base:
            "*":
                - beats.repository
                - beats.filebeat.install
                - beats.filebeat.config
                - beats.filebeat.service
                - beats.filebeat.purge
                - beats.metricbeat.install
                - beats.metricbeat.config
                - beats.metricbeat.service
                - beats.metricbeat.purge
                - beats.purge

platforms:
    - name: debian-jessie
    - name: ubuntu-14.04
    - name: ubuntu-16.04
    - name: centos-6
    - name: centos-7
      driver_config:
        run_command: /usr/lib/systemd/systemd

suites:
    - name: default
